input_dir: /data/InputFastqDir


############control raw fastq dir
output_dir: /data/InputFastqDir/Output

genome_dir: /data/ref


know_dbsnp_vcf: /data/ref/dbsnp_146.hg38.vcf.gz
know_indels: /data/ref/Homo_sapiens_assembly38.known_indels.vcf.gz
gold_standard_indels: /data/ref/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz
1000G_snpshigh_confidence: /data/ref/1000G_phase1.snps.high_confidence.hg38.vcf.gz
interval_list: /data/ref/wgs_calling_regions.hg38.interval_list


af_only_gnomad: /data/ref/af-only-gnomad.hg38.vcf.gz
gatk_panel_of_normal: /data/ref/1000g_pon.hg38.vcf.gz



exac_common_knownsite: /data/ref/small_exac_common_3.hg38.vcf.gz


hg38gene_bed: /data/bed_files/geneV38.panel.bed
hg38access_bed: /data/bed_files/access-excludes.hg38.bed

params:
  genome_name: "GRCh38.d1.vd1"
  thread_num: 64

Evaluate:
  gold_vcf: data/eval/NA12878_S1.SV.vcf
  highConfidentRegion: data/eval/ConfidentRegions.bed
